### ISSUE TITLE
Feature Request - Lock Image Aspect Ratio

### ISSUE THREAD

**Issue by billiemead** [easylogic/editor#112] opened 2021-03-05 07:52 UTC
When importing image assets it is critical that the original aspect ratio is locked. But there also should be a way to disable height and width ratio lock.

Cheers,
Billie

**Comment by easylogic** [comment] 2021-03-05 12:11
Thanks for your report. 

I will add this feature In the near future.

**Comment by billiemead** [comment] 2021-03-05 22:48
@easylogic 
My pleasure. Again, I cant believe how incredibly powerful easylogic is. I'd love to find out what eventual direction you are headed with it and who you are targeting. I started doing some mobile app mockups and fell in love.

**Comment by easylogic** [comment] 2021-03-06 17:06
@billiemead 

The basic direction of the editor is to make a quality editor like Figma with pure CSS/SVG based web technology.

The reason I think so is that if the content created by designers and the content created in other design tools can all be handled directly on the web, the speed of creating the entire product will be increased.

By doing so, the ultimate goal is to get designers to the point where they can create products right away without going through developers.

**Comment by easylogic** [comment] 2021-03-10 15:35
hi @billiemead 

I released image aspect ratio. 

you can test it on site with new version (v0.10.6). 

To use this feature, you need to press shift key. 


https://user-images.githubusercontent.com/591983/110654431-77b71f00-8201-11eb-9d02-fca53723903f.mov

**Comment by billiemead** [comment] 2021-03-10 16:19
@easylogic 
Nice one, I will pull later and check it out straight away!

**Closed** 2021-03-12 15:24 UTC
Labels: enhancement
